//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS335s2_A2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryComment
    {
        public int CategoryCommentID { get; set; }
        public int CategoryID { get; set; }
        public string Comment { get; set; }
        public string MadeBy { get; set; }
        public System.DateTime CommentDate { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
