//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS335s2_A2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCustomer
    {
        public MyCustomer()
        {
            this.MyOrders = new HashSet<MyOrder>();
        }
    
        public string CustomerID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual ICollection<MyOrder> MyOrders { get; set; }
    }
}
