//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS335s2_A2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyOrder
    {
        public string OrderID { get; set; }
        public string CustomerID { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int Items { get; set; }
    
        public virtual MyCustomer MyCustomer { get; set; }
    }
}
